-- CONSULTAS SIMPLES
SELECT IDFAB, IDPRODUCTO, DESCRIPCION AS CARACTERISTICAS, PRECIO FROM PRODUCTOS;
SELECT IDFAB AS FABRICANTE, IDPRODUCTO, DESCRIPCION FROM PRODUCTOS;
SELECT NOMBRE, REPCLIE, LIMITECREDITO FROM CLIENTES;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM OFICINAS;
SELECT * FROM EMPLEADOS;
SELECT * FROM CLIENTES;

-- CONSULTAS CON COLUMNAS CALCULADAS


-- CONSULTAS CON ORDENACION DE FILAS
SELECT NOMBRE, OFICINA, CONTRATO FROM EMPLEADOS ORDER BY CONTRATO ASC;
SELECT OFICINA, OBJETIVO, VENTAS FROM OFICINAS ORDER BY 1 ASC;
SELECT NOMBRE, REPCLIE, LIMITECREDITO FROM CLIENTES ORDER BY NOMBRE DESC;
SELECT NOMBRE, CONTRATO, VENTAS FROM EMPLEADOS ORDER BY 2 ASC;
SELECT FAB, PRODUCTO FROM PEDIDOS ORDER BY 1 ASC;
SELECT FAB, PRODUCTO FROM PEDIDOS ORDER BY 1 DESC;

-- CONSULTAS UTILIZANDO LA CLAUSULA (DISTINC/ALL)
SELECT ALL * FROM PEDIDOS;
SELECT DISTINCT CLIENTE FROM PEDIDOS;
SELECT DISTINCT REGION FROM OFICINAS;
SELECT ALL REGION FROM OFICINAS;
SELECT ALL JEFE FROM EMPLEADOS;
SELECT DISTINCT JEFE FROM EMPLEADOS;

-- CONSULTAS UTILIZANDO LA CLAUSULA (TOP)
SELECT TOP 10 * FROM CLIENTES ORDER BY REPCLIE DESC;
SELECT TOP 7 * FROM PRODUCTOS ORDER BY DESCRIPCION ASC;
SELECT TOP 3 * FROM OFICINAS ORDER BY REGION DESC;
SELECT TOP 15 FAB, PRODUCTO, IMPORTE FROM PEDIDOS ORDER BY PRODUCTO DESC;
SELECT TOP 4 REGION, OBJETIVO, VENTAS FROM OFICINAS ORDER BY REGION DESC;
SELECT TOP 15 REPCLIE, NOMBRE, LIMITECREDITO FROM CLIENTES ORDER BY NOMBRE DESC;
SELECT TOP 10 DESCRIPCION, PRECIO, EXISTENCIAS FROM PRODUCTOS ORDER BY DESCRIPCION ASC;
SELECT TOP(20) PERCENT FAB, PRODUCTO, IMPORTE FROM PEDIDOS ORDER BY PRODUCTO ASC;

-- CONSULTAS UTILIZANDO LA CLAUSULA WHERE
SELECT NOMBRE, OFICINA, EDAD FROM EMPLEADOS WHERE OFICINA > 12 AND EDAD > 30;
SELECT NUMEMP, NOMBRE, VENTAS, CUOTA FROM EMPLEADOS WHERE VENTAS > CUOTA;
SELECT NUMEMP, NOMBRE, CONTRATO FROM EMPLEADOS WHERE CONTRATO < '1998-01-01';
SELECT NUMEMP, NOMBRE, CONTRATO FROM EMPLEADOS WHERE CONTRATO < '1998-01-01';
SELECT OFICINA, VENTAS, OBJETIVO FROM OFICINAS WHERE VENTAS < 0.8 * OBJETIVO;
SELECT OFICINA, DIR FROM OFICINAS WHERE DIR = 108

-- CONSULTAS UTILIZANDO LA CLAUSULA WHERE (BETWEEN)
SELECT NOMBRE, LIMITECREDITO FROM CLIENTES WHERE LIMITECREDITO BETWEEN 20000 AND 45000;
SELECT DESCRIPCION, EXISTENCIAS, PRECIO FROM PRODUCTOS WHERE EXISTENCIAS NOT BETWEEN 5 AND 37;
SELECT NUMPEDIDO, CLIENTE, PRODUCTO, CANT FROM PEDIDOS WHERE CANT BETWEEN 5 AND 10;

--  INSERTAR REGISTROS
-- TABLA EMPLEADOS
IF NOT EXISTS (SELECT * FROM EMPLEADOS WHERE NUMEMP = 111)
BEGIN
    INSERT INTO EMPLEADOS
    (NUMEMP, NOMBRE, EDAD, OFICINA, TITULO, CONTRATO, JEFE, CUOTA, VENTAS)
    VALUES
    (111, 'GENARO VICENT', 55, 11, 'REPRESENTANTE', '1998-05-15', 103, 350000.00, 250000.00)
END

IF NOT EXISTS (SELECT * FROM EMPLEADOS WHERE NUMEMP = 112)
BEGIN
    INSERT INTO EMPLEADOS
    (NUMEMP, NOMBRE, EDAD, OFICINA, TITULO, CONTRATO, JEFE, CUOTA, VENTAS)
    VALUES
    (112, 'JUAN JOSE', 21, 21, NULL, '1997-05-04', NULL, 850000.00, 730000.00)
END

IF NOT EXISTS (SELECT * FROM EMPLEADOS WHERE NUMEMP = 113)
BEGIN
    INSERT INTO EMPLEADOS
    (NUMEMP, NOMBRE, EDAD, OFICINA, TITULO, CONTRATO, JEFE, CUOTA, VENTAS)
    VALUES
    (113, 'JOSE JUAN', 54, 12, 'FIR GRAL', '1997-06-12', 102, 500000.00, 250000.00)
END

IF NOT EXISTS (SELECT * FROM EMPLEADOS WHERE NUMEMP = 114)
BEGIN
    INSERT INTO EMPLEADOS
    (NUMEMP, NOMBRE, EDAD, OFICINA, TITULO, CONTRATO, JEFE, CUOTA, VENTAS)
    VALUES
    (114, 'LUIS JOSE', 45, 12, NULL, '1998-08-11', NULL, NULL, 320000.00)
END

IF NOT EXISTS (SELECT * FROM EMPLEADOS WHERE NUMEMP = 115)
BEGIN
    INSERT INTO EMPLEADOS
    (NUMEMP, NOMBRE, EDAD, OFICINA, TITULO, CONTRATO, JEFE, CUOTA, VENTAS)
    VALUES
    (115, 'JOSE ANTONIO', 42, 11, 'REPRESENTANTE', '1995-05-02', 107, 200000.00, 300000.00)
END

-- TABLA CLIENTES
IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 28)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2125, 'ELOISA MONTES', 101, 70000.00)
END

IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 29)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2126, 'JOSE ALVARO', 110, 20000.00)
END

IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 30)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2127, 'ALVARO JUAN', 101, 56000.00)
END

IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 31)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2128, 'JOSE LUIS', 112, 41000.00)
END

IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 32)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2129, 'ERNESTO ALVARO', 106, 23000.00)
END

IF NOT EXISTS (SELECT * FROM CLIENTES WHERE ID = 33)
BEGIN
    INSERT INTO CLIENTES
    (NUMCLIE, NOMBRE, REPCLIE, LIMITECREDITO)
    VALUES
    (2130, 'ERENDIRA JIMENEZ', 105, 18000.00)
END

-- CONSULTAS UTILIZANDO LA CLAUSULA WHERE (IN)
SELECT NOMBRE, EDAD, JEFE FROM EMPLEADOS WHERE JEFE IN (102, 105);
SELECT NOMBRE, REPCLIE FROM CLIENTES WHERE REPCLIE IN (103, 105);
SELECT IDFAB, DESCRIPCION, PRECIO FROM PRODUCTOS WHERE DESCRIPCION IN ('MANIVELA', 'RED');

-- CONSULTAS UTILIZANDO LA CLAUSULA WHERE (IS NULL)
SELECT OFICINA, CIUDAD, OBJETIVO FROM OFICINAS WHERE OBJETIVO IS NOT NULL;
SELECT NOMBRE, TITULO FROM EMPLEADOS WHERE TITULO IS NOT NULL;
SELECT NOMBRE, OFICINA, CUOTA FROM EMPLEADOS WHERE CUOTA IS NOT NULL;

-- CONSULTAS UTILIZANDO LA CLAUSULA WHERE (LIKE)
SELECT NOMBRE, TITULO, VENTAS FROM EMPLEADOS WHERE NOMBRE LIKE '%JUAN%';
SELECT NOMBRE, TITULO, VENTAS FROM EMPLEADOS WHERE NOMBRE NOT LIKE '%JUAN%';
SELECT NOMBRE, EDAD, CUOTA FROM EMPLEADOS WHERE NOMBRE LIKE '__R%';
SELECT NOMBRE, JEFE FROM EMPLEADOS WHERE NOMBRE LIKE '__I%';
SELECT NOMBRE, JEFE FROM EMPLEADOS WHERE NOMBRE LIKE 'JOSE%';
SELECT NOMBRE, REPCLIE FROM CLIENTES WHERE NOMBRE LIKE '___I%';
SELECT NOMBRE, REPCLIE FROM CLIENTES WHERE NOMBRE NOT LIKE '___I%';
SELECT NOMBRE, LIMITECREDITO FROM CLIENTES WHERE NOMBRE LIKE '_U%';
SELECT NOMBRE, LIMITECREDITO FROM CLIENTES WHERE NOMBRE LIKE '%ALVARO%';
SELECT NOMBRE, LIMITECREDITO FROM CLIENTES WHERE NOMBRE LIKE 'ALVARO%';
SELECT NOMBRE, LIMITECREDITO FROM CLIENTES WHERE NOMBRE NOT LIKE 'ALVARO%';
SELECT NUMEMP, NOMBRE FROM EMPLEADOS WHERE NOMBRE LIKE 'A%' OR NOMBRE LIKE 'J%';
SELECT NUMEMP, NOMBRE FROM EMPLEADOS WHERE NOMBRE LIKE 'C%' OR NOMBRE LIKE 'E%';
SELECT NUMCLIE, NOMBRE FROM CLIENTES WHERE NOMBRE LIKE '[A-C]%';
SELECT NUMCLIE, NOMBRE FROM CLIENTES WHERE NOMBRE LIKE '[S-V]%'
SELECT NUMCLIE, NOMBRE FROM CLIENTES WHERE NOMBRE LIKE 'JO%';
SELECT NUMCLIE, NOMBRE FROM CLIENTES WHERE NOMBRE LIKE 'J[^O]%';
SELECT NUMCLIE, NOMBRE FROM CLIENTES WHERE NOMBRE LIKE 'C[^R]%';