
CREATE IF NOT EXISTS DATABASE database_managers

USE database_managers

-- CREATE TABLE EMPLEADOS
IF OBJECT_ID('TB_EMPLEADOS', 'TB_EMPLEADOS') IS NULL
BEGIN
    CREATE TABLE EMPLEADOS (
        NUMEMP INT NOT NULL,
        NOMBRE VARCHAR(15) NOT NULL,
        EDAD INT NOT NULL,
        OFICINA INT NULL,
        TITULO VARCHAR(20) NOT NULL,
        CONTRATO DATE NOT NULL,
        JEFE INT NULL,
        CUOTA DECIMAL(18, 2) NULL,
        VENTAS DECIMAL(18, 2) NOT NULL 
    )
END;

-- CREATE TABLE OFICINAS
IF OBJECT_ID('TB_OFICINAS', 'TB_OFICINAS') IS NULL
BEGIN
    CREATE TABLE OFICINAS (
        OFICINA INT NOT NULL,
        CIUDAD VARCHAR(20) NOT NULL,
        REGION VARCHAR(20) NOT NULL,
        DIR INT NULL,
        OBJETIVO DECIMAL(18, 2) NULL,
        VENTAS DECIMAL(18, 2) NULL
    )
END;

-- CREATE TABLE CLIENTES
IF OBJECT_ID('TB_CLIENTES', 'TB_CLIENTES') IS NULL
BEGIN
    CREATE TABLE CLIENTES (
        ID INT IDENTITY(1, 1) NOT NULL,
        NUMCLIE INT NOT NULL,
        NOMBRE VARCHAR(30) NOT NULL,
        REPCLIE INT NOT NULL,
        LIMITECREDITO DECIMAL(18, 2) NOT NULL
    )
    
    ALTER TABLE [CLIENTES] ADD CONSTRAINT [PK_OFICINA_ID] PRIMARY KEY ([ID])
END;

-- CREATE TABLE PRODUCTOS
IF OBJECT_ID('TB_PRODUCTOS', 'TB_PRODUCTOS') IS NULL
BEGIN
    CREATE TABLE PRODUCTOS (
        IDFAB VARCHAR(3) NOT NULL,
        IDPRODUCTO VARCHAR(7) NOT NULL,
        DESCRIPCION VARCHAR(30) NOT NULL,
        PRECIO DECIMAL(18, 2) NOT NULL,
        EXISTENCIAS INT NOT NULL
    )
END;

-- CREATE TABLE PEDIDOS
IF OBJECT_ID('TB_PEDIDOS', 'TB_PEDIDOS') IS NULL
BEGIN
    CREATE TABLE PEDIDOS (
        IDCODIGO INT IDENTITY(1, 1) NOT NULL,
        NUMPEDIDO INT NOT NULL,
        FECHAPEDIDO DATE NOT NULL,
        CLIENTE INT NOT NULL,
        REP INT NOT NULL,
        FAB VARCHAR(3) NOT NULL,
        PRODUCTO VARCHAR(7) NOT NULL,
        CANT INT NOT NULL,
        IMPORTE DECIMAL(18, 2) NOT NULL
    )

    ALTER TABLE [PEDIDOS] ADD CONSTRAINT [PK_IDCODIGO] PRIMARY KEY ([IDCODIGO])
END;