-- INSERT VALUES FOR TABLE PRODUCTOS

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '112')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('FEA', '112', 'CUBO', 148.00, 115)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '114')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('FEA', '114', 'CUBO', 243.00, 15)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '2A44C')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('REI', '2A44C', 'JUNTA', 79.00, 210)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '2A44G')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('REI', '2A44G', 'PAZ', 350.00, 14)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '2A44L')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('REI', '2A44L', 'BOMBA L', 4500.00, 12)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '2A44R')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('REI', '2A44R', 'BOMBA R', 4500.00, 2)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '41003')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('BIC', '41003', 'MANIVELA', 652.00, 3)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4100X')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4100X', 'JUNTA', 26.00, 37)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4100Y')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4100Y', 'EXTRACTOR', 2888.00, 25)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4100Z')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4100Z', 'MONT', 2625.00, 28)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4101')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4101', 'ARANDELA', 58.00, 277)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4102')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4102', 'BISAGRA', 80.00, 167)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4103')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4103', 'ART T3', 112.00, 207)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4103')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4103', 'ART T3', 112.00, 207)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '4104')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('ACI', '4104', 'ART T4', 123.00, 139)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '41089')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('BIC', '41089', 'RODAMIENTO', 225.00, 78)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '41672')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('BIC', '41672', 'PLATO', 180.00, 0)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '773C')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('IMM', '773C', 'REOSTATO', 975.00, 28)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '775C')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('IMM', '775C', 'REOSTATO2', 1425.00, 5)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '887H')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('IMM', '887H', 'CAJA CLAVOS', 54.00, 223)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '887P')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('IMM', '887P', 'PORNO', 25.00, 24)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = '887X')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('IMM', '887X', 'MANIVELA', 475.00, 32)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = 'XK47')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('QSA', 'XK47', 'RED', 355.00, 38)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = 'XK48')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('QSA', 'XK48', 'RED', 134.00, 203)
END

IF NOT EXISTS (SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = 'XK48A')
BEGIN
    INSERT INTO PRODUCTOS
    (IDFAB, IDPRODUCTO, DESCRIPCION, PRECIO, EXISTENCIAS)
    VALUES
    ('QSA', 'XK48A', 'RED', 117.00, 37)
END